name: Bot Automation

on:
  schedule:
    # Cron expressions to run from 7 AM to 4 AM the next day (UTC time).
    - cron: "0 7 * * *"  # 7:00 AM UTC
    - cron: "0 10 * * *" # 10:00 AM UTC
    - cron: "0 13 * * *" # 1:00 PM UTC
    - cron: "0 16 * * *" # 4:00 PM UTC
    - cron: "0 19 * * *" # 7:00 PM UTC
    - cron: "0 22 * * *" # 10:00 PM UTC
    - cron: "0 1 * * *"  # 1:00 AM UTC
    - cron: "0 4 * * *"  # 4:00 AM UTC

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install PyGithub
      - name: Execute bot
        run: python hi.py
